# Generated by Django 4.1.3 on 2023-02-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
