# Generated by Django 4.1.3 on 2023-02-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_wishlist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
    ]
