# Generated by Django 4.1.7 on 2023-02-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_wishlist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
