# Generated by Django 4.1.7 on 2023-02-20 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
